In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pygraphon.utils.utils_matrix import permute_matrix
import numpy as np

In [12]:
a = np.array([[1, 2,3], [4,5,6], [7,8,9]])
permutation = (1,0,2)
b = a.copy()
b[permutation,:] = a[:,permutation]
print(a,"\n",b)
b[:,permutation] = b[permutation,:]
print(a,"\n",b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[5 4 6]
 [2 1 3]
 [8 7 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a

array([[1, 2],
       [3, 4]])

In [6]:
b

array([[4, 3],
       [2, 1]])